# GitHub Sponsors - 이 레포지토리 우측 "Sponsor" 버튼에 사용됩니다.
# GitHub에서 스폰서 프로필 설정: https://github.com/sponsors
# 설정 후 아래에 사용자명을 넣으면 버튼이 활성화됩니다.

github: [jaloveeye]

# 다른 후원 플랫폼을 쓰려면 아래처럼 추가할 수 있습니다 (선택).
# patreon: username
# ko_fi: username
# buy_me_a_coffee: username
# custom: ['https://your-link.com']
